export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "caetgory/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "caetgory/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "caetgory/FETCH_CATEGORIES_FAILED",
};
